# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate html
        run: bash ./generate_gallery_html.sh

      - name: Deploy html to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          cp gallery.html index.html
          rm gallery.html
          git add index.html
          git commit -m "Gallery"
          git push origin gh-pages --force
